name: flutter_application_22
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  file_picker: ^8.1.2
  flutter:
    sdk: flutter
  flutter_slidable: ^3.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  path: ^1.9.0
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  provider: ^6.1.2
  share_plus: ^10.0.2
  shared_preferences: ^2.3.2

dev_dependencies:
  build_runner: ^2.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.0
  read_more_text: ^0.0.5
flutter_icons:
  android: true
  ios: false
  image_path: "assets/logo.png"  # Path to your icon file
flutter:
  uses-material-design: true
